/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QuasarAlphaImport } from './routes/quasar-alpha'
import { Route as PromptImport } from './routes/prompt'
import { Route as O3MiniHighImport } from './routes/o3-mini-high'
import { Route as LlamaScoutImport } from './routes/llama-scout'
import { Route as LlamaMaverickImport } from './routes/llama-maverick'
import { Route as Gemini20FlashImport } from './routes/gemini-20-flash'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const QuasarAlphaRoute = QuasarAlphaImport.update({
  id: '/quasar-alpha',
  path: '/quasar-alpha',
  getParentRoute: () => rootRoute,
} as any)

const PromptRoute = PromptImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => rootRoute,
} as any)

const O3MiniHighRoute = O3MiniHighImport.update({
  id: '/o3-mini-high',
  path: '/o3-mini-high',
  getParentRoute: () => rootRoute,
} as any)

const LlamaScoutRoute = LlamaScoutImport.update({
  id: '/llama-scout',
  path: '/llama-scout',
  getParentRoute: () => rootRoute,
} as any)

const LlamaMaverickRoute = LlamaMaverickImport.update({
  id: '/llama-maverick',
  path: '/llama-maverick',
  getParentRoute: () => rootRoute,
} as any)

const Gemini20FlashRoute = Gemini20FlashImport.update({
  id: '/gemini-20-flash',
  path: '/gemini-20-flash',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/gemini-20-flash': {
      id: '/gemini-20-flash'
      path: '/gemini-20-flash'
      fullPath: '/gemini-20-flash'
      preLoaderRoute: typeof Gemini20FlashImport
      parentRoute: typeof rootRoute
    }
    '/llama-maverick': {
      id: '/llama-maverick'
      path: '/llama-maverick'
      fullPath: '/llama-maverick'
      preLoaderRoute: typeof LlamaMaverickImport
      parentRoute: typeof rootRoute
    }
    '/llama-scout': {
      id: '/llama-scout'
      path: '/llama-scout'
      fullPath: '/llama-scout'
      preLoaderRoute: typeof LlamaScoutImport
      parentRoute: typeof rootRoute
    }
    '/o3-mini-high': {
      id: '/o3-mini-high'
      path: '/o3-mini-high'
      fullPath: '/o3-mini-high'
      preLoaderRoute: typeof O3MiniHighImport
      parentRoute: typeof rootRoute
    }
    '/prompt': {
      id: '/prompt'
      path: '/prompt'
      fullPath: '/prompt'
      preLoaderRoute: typeof PromptImport
      parentRoute: typeof rootRoute
    }
    '/quasar-alpha': {
      id: '/quasar-alpha'
      path: '/quasar-alpha'
      fullPath: '/quasar-alpha'
      preLoaderRoute: typeof QuasarAlphaImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gemini-20-flash': typeof Gemini20FlashRoute
  '/llama-maverick': typeof LlamaMaverickRoute
  '/llama-scout': typeof LlamaScoutRoute
  '/o3-mini-high': typeof O3MiniHighRoute
  '/prompt': typeof PromptRoute
  '/quasar-alpha': typeof QuasarAlphaRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gemini-20-flash': typeof Gemini20FlashRoute
  '/llama-maverick': typeof LlamaMaverickRoute
  '/llama-scout': typeof LlamaScoutRoute
  '/o3-mini-high': typeof O3MiniHighRoute
  '/prompt': typeof PromptRoute
  '/quasar-alpha': typeof QuasarAlphaRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/gemini-20-flash': typeof Gemini20FlashRoute
  '/llama-maverick': typeof LlamaMaverickRoute
  '/llama-scout': typeof LlamaScoutRoute
  '/o3-mini-high': typeof O3MiniHighRoute
  '/prompt': typeof PromptRoute
  '/quasar-alpha': typeof QuasarAlphaRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gemini-20-flash'
    | '/llama-maverick'
    | '/llama-scout'
    | '/o3-mini-high'
    | '/prompt'
    | '/quasar-alpha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gemini-20-flash'
    | '/llama-maverick'
    | '/llama-scout'
    | '/o3-mini-high'
    | '/prompt'
    | '/quasar-alpha'
  id:
    | '__root__'
    | '/'
    | '/gemini-20-flash'
    | '/llama-maverick'
    | '/llama-scout'
    | '/o3-mini-high'
    | '/prompt'
    | '/quasar-alpha'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Gemini20FlashRoute: typeof Gemini20FlashRoute
  LlamaMaverickRoute: typeof LlamaMaverickRoute
  LlamaScoutRoute: typeof LlamaScoutRoute
  O3MiniHighRoute: typeof O3MiniHighRoute
  PromptRoute: typeof PromptRoute
  QuasarAlphaRoute: typeof QuasarAlphaRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Gemini20FlashRoute: Gemini20FlashRoute,
  LlamaMaverickRoute: LlamaMaverickRoute,
  LlamaScoutRoute: LlamaScoutRoute,
  O3MiniHighRoute: O3MiniHighRoute,
  PromptRoute: PromptRoute,
  QuasarAlphaRoute: QuasarAlphaRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/gemini-20-flash",
        "/llama-maverick",
        "/llama-scout",
        "/o3-mini-high",
        "/prompt",
        "/quasar-alpha"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/gemini-20-flash": {
      "filePath": "gemini-20-flash.tsx"
    },
    "/llama-maverick": {
      "filePath": "llama-maverick.tsx"
    },
    "/llama-scout": {
      "filePath": "llama-scout.tsx"
    },
    "/o3-mini-high": {
      "filePath": "o3-mini-high.tsx"
    },
    "/prompt": {
      "filePath": "prompt.tsx"
    },
    "/quasar-alpha": {
      "filePath": "quasar-alpha.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
